### ISSUE TITLE
move random() to the separate js module - random.js

### ISSUE THREAD

**Issue by gerkirill** [gerkirill/bouncing-balls#1]
- move random() to the separate js module - random.js
 - import it into main.js and make sure everything still works with `parcel index.html` command

**Comment by gerkirill** [comment]
fixed in ca923e2204d236ea6ddcfe719aad2740f3e5d8e2

**Comment by AnatoliiMazur** [comment]
5e042284305df94a214b1271ea1ad93cbd8ecc17
